# Exercise B: Write a program to compute the pagerank of a graph.

In [436]:
import numpy as np
import pandas as pd

In [344]:
# The input for the program will be the adjacency matrix M of the graph.
# We will iterate the equation r=(1-d)/N +dMr, where r is the column of page ranks, d=0.85 is the damping factor, 
# and N is the number of rows/columns of M, until the change in each component of r is < epsilon=.01.

In [437]:
# Initialize adjacency matrix M of the graph.
M=np.matrix([[0,0,0,1,0],
             [1,0,0.5,0,0],
             [0,0.5,0,0,0],
             [0,0.5,0,0,0],
             [0,0,0.5,0,0]])
# Initialize d=0.85.
d=0.85
# Initialize all pageranks as 1.
N=np.shape(M)[0]
P=np.array([1,1,1,1,1])

In [447]:
P=np.matrix([1,1,1,1,1])
def PageRank(M,T):
    P=np.matrix([1,1,1,1,1])
    thresh=1
    while thresh>T:
        Q=(1-d)/N+d*(np.inner(M,P))
        rows,cols = P.shape
        thresh=max(abs(P[0,0]-Q[0]),abs(P[0,1]-Q[1]),abs(P[0,2]-Q[2]),abs(P[0,3]-Q[3]),abs(P[0,4]-Q[4]))
        S=np.matrix([float(Q[0]),float(Q[1]),float(Q[2]),float(Q[3]),float(Q[4])])
        P=pd.DataFrame(P)
        S=pd.DataFrame(S)
        for r in range(rows):
            for c in range(cols):
                P[c][r]=S[c][r]
        P=np.matrix(P)
        S=np.matrix(S)
        print(S,thresh)

In [448]:
PageRank(M,.01)

[[0.88  1.305 0.455 0.455 0.455]] [[0.545]]
[[0.41675  0.971375 0.584625 0.584625 0.223375]] [[0.46325]]
[[0.52693125 0.63270312 0.44283438 0.44283438 0.27846562]] [[0.33867188]]
[[0.40640922 0.66609617 0.29889883 0.29889883 0.21820461]] [[0.14393555]]
[[0.284064   0.50247984 0.31309087 0.31309087 0.157032  ]] [[0.16361633]]
[[0.29612724 0.40451802 0.24355393 0.24355393 0.16306362]] [[0.09796181]]
[[0.23702084 0.38521858 0.20192016 0.20192016 0.13351042]] [[0.0591064]]
[[0.20163214 0.31728378 0.1937179  0.1937179  0.11581607]] [[0.06793479]]
[[0.19466021 0.28371742 0.16484561 0.16484561 0.11233011]] [[0.03356636]]
[[0.17011877 0.26552056 0.1505799  0.1505799  0.10005938]] [[0.02454144]]
[[0.15799292 0.23859741 0.14284624 0.14284624 0.09399646]] [[0.02692315]]
[[0.1514193  0.22500363 0.1314039  0.1314039  0.09070965]] [[0.01359378]]
[[0.14169331 0.21455307 0.12562654 0.12562654 0.08584666]] [[0.01045057]]
[[0.13678256 0.2038306  0.12118505 0.12118505 0.08339128]] [[0.01072247]]
[[0.1330

C:\Users\Kenny\AppData\Local\Temp\ipykernel_13120\421010696.py:14: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  P[c][r]=S[c][r]


# 15 iterations to get epsilon <.01

In [192]:
M=np.matrix([[0,0,0,1,0],
             [1,0,1,0,0],
             [0,1,0,0,0],
             [0,1,0,0,0],
             [0,0,0,1,0]])
P=np.matrix([1,1,1,1,1])

In [193]:
np.inner(M,P)

matrix([[1],
        [2],
        [1],
        [1],
        [1]])

In [195]:
Q=(1-d)/N+d*(np.inner(M,P))
Q

matrix([[0.88],
        [1.73],
        [0.88],
        [0.88],
        [0.88]])

In [65]:
Q=(1-d)/N+d*(np.inner(M,P))

In [67]:
Q

matrix([[0.88, 1.73, 0.88, 0.88, 0.88]])

In [202]:
P[0,0]

1

In [99]:
(1-d)/N

0.030000000000000006

In [110]:
np.shape(M)

(5, 5)

In [121]:
np.shape(P)

(5, 1)

In [196]:
P

matrix([[1, 1, 1, 1, 1]])

In [136]:
P[0]

1

In [172]:
np.shape(Q)

(1, 5)

In [257]:
M=np.matrix([[0,0,0,1,0],
             [1,0,1,0,0],
             [0,1,0,0,0],
             [0,1,0,0,0],
             [0,0,0,1,0]])
M

matrix([[0, 0, 0, 1, 0],
        [1, 0, 1, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 1, 0]])

In [258]:
P=np.matrix([1,1,1,1,1])
P

matrix([[1, 1, 1, 1, 1]])

In [260]:
P[0,2]=5
print(P)
M[1,2]=41324
M

[[1 1 5 1 1]]


matrix([[    0,     0,     0,     1,     0],
        [    1,     0, 41324,     0,     0],
        [    0,     1,     0,     0,     0],
        [    0,     1,     0,     0,     0],
        [    0,     0,     0,     1,     0]])

In [261]:
print(Q)
float(Q[2])

[[0.88]
 [1.73]
 [0.88]
 [0.88]
 [0.88]]


0.88

In [262]:
P[0,1]=float(Q[2])
P

matrix([[1, 0, 5, 1, 1]])

In [267]:
Q[0]=P[0,1]
print(Q)
print(P)

[[0.  ]
 [1.73]
 [0.88]
 [0.88]
 [0.88]]
[[1 0 5 1 1]]


In [434]:
# Set damping factor d=0.85.
d=0.85
# Initialize PageRanks to 1.
A=B=C=D=E=1
# Initialize threshold
T=1
while T>.01:
    A_new=(1-d)/5+d*D
    B_new=(1-d)/5+d*(A+C/2)
    C_new=(1-d)/5+d*(B/2)
    D_new=(1-d)/5+d*(B/2)
    E_new=(1-d)/5+d*(C/2)
    T=max(abs(A-A_new),abs(B-B_new),abs(C-C_new),abs(D-D_new),abs(E-E_new))
    print(A_new,B_new,C_new,D_new,E_new,T)
    A=A_new
    B=B_new
    C=C_new
    D=D_new
    E=E_new

0.88 1.305 0.455 0.455 0.455 0.5449999999999999
0.41675 0.971375 0.584625 0.584625 0.223375 0.46325
0.52693125 0.6327031249999999 0.442834375 0.442834375 0.278465625 0.33867187500000007
0.40640921875 0.666096171875 0.29889882812499996 0.29889882812499996 0.218204609375 0.14393554687500004
0.28406400390625 0.502479837890625 0.31309087304687505 0.31309087304687505 0.15703200195312497 0.16361633398437503
0.2961272420898438 0.40451802436523443 0.24355393110351561 0.24355393110351561 0.1630636210449219 0.09796181352539057
0.23702084143798827 0.3852185764953614 0.20192016035522461 0.20192016035522461 0.13351042071899413 0.059106400651855545
0.2016321363019409 0.3172837833732605 0.19371789501052858 0.19371789501052858 0.11581606815097045 0.06793479312210088
0.1946602107589493 0.2837174212361244 0.16484560793363573 0.16484560793363573 0.11233010537947466 0.033566362137136097
0.17011876674359036 0.2655205625169021 0.15057990402535287 0.15057990402535287 0.10005938337179518 0.024541444015358932


In [449]:
# Set damping factor d=0.85.
d=0.85
# Initialize PageRanks to 1.
A=B=C=D=E=1
# Initialize threshold
T=1
while T>.01:
    A_new=(1-d)/5+d*D
    B_new=(1-d)/5+d*(A+C/2)
    C_new=(1-d)/5+d*(B/2)
    D_new=(1-d)/5+d*(B/2)
    E_new=(1-d)/5+d*(C/2)
    T=max(abs(A-A_new),abs(B-B_new),abs(C-C_new),abs(D-D_new),abs(E-E_new))
    print(A_new,B_new,C_new,D_new,E_new,T)
    A=A_new
    B=B_new
    C=C_new
    D=D_new
    E=E_new

0.88 1.305 0.455 0.455 0.455 0.5449999999999999
0.41675 0.971375 0.584625 0.584625 0.223375 0.46325
0.52693125 0.6327031249999999 0.442834375 0.442834375 0.278465625 0.33867187500000007
0.40640921875 0.666096171875 0.29889882812499996 0.29889882812499996 0.218204609375 0.14393554687500004
0.28406400390625 0.502479837890625 0.31309087304687505 0.31309087304687505 0.15703200195312497 0.16361633398437503
0.2961272420898438 0.40451802436523443 0.24355393110351561 0.24355393110351561 0.1630636210449219 0.09796181352539057
0.23702084143798827 0.3852185764953614 0.20192016035522461 0.20192016035522461 0.13351042071899413 0.059106400651855545
0.2016321363019409 0.3172837833732605 0.19371789501052858 0.19371789501052858 0.11581606815097045 0.06793479312210088
0.1946602107589493 0.2837174212361244 0.16484560793363573 0.16484560793363573 0.11233010537947466 0.033566362137136097
0.17011876674359036 0.2655205625169021 0.15057990402535287 0.15057990402535287 0.10005938337179518 0.024541444015358932
